### PR TITLE
fix(backend): fix swagger issue in deployed application tm-128

### LINKED ISSUE #128: fix: Swagger does not work in deployment
### Describe your issue

Swagger routes are not loaded in deployed application

### Steps to reproduce

1. Open Swagger in a deployed application

### What was the actual result?

Swagger routes are not visible

### What was the expected result?

Swagger routes should be visible

### Put here any screenshots or videos (optional)

_No response_

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

### PR DESCRIPTION
**Pull request by fshabanov**
Fixes #128

### CODE REVIEW

**Review by what1s1ove — APPROVED** [review]

File: apps/backend/src/libs/modules/server-application/base-server-application-api.ts [hunk 1]
```diff
@@ -29,10 +29,11 @@ class BaseServerApplicationApi implements ServerApplicationApi {
 	}
 
 	public generateDoc(title: string): ReturnType<typeof swaggerJsdoc> {
-		const isProduction =
-			this.config.ENV.APP.ENVIRONMENT === AppEnvironment.PRODUCTION;
+		const isDeployedApplication =
```
Comment (what1s1ove) [inline apps/backend/src/libs/modules/server-application/base-server-application-api.ts:32]:
```suggestion
		const isDevelopmentApplication = this.config.ENV.APP.ENVIRONMENT === AppEnvironment.LOCAL;
```
can we do something like this?

File: apps/backend/src/libs/modules/server-application/base-server-application-api.ts [hunk 2]
```diff
@@ -29,10 +29,10 @@ class BaseServerApplicationApi implements ServerApplicationApi {
 	}
 
 	public generateDoc(title: string): ReturnType<typeof swaggerJsdoc> {
-		const isProduction =
-			this.config.ENV.APP.ENVIRONMENT === AppEnvironment.PRODUCTION;
+		const isDevelopmentApplication =
```
Comment (what1s1ove) [inline apps/backend/src/libs/modules/server-application/base-server-application-api.ts:32]:
```suggestion
		const isLocal =
```
simplify

**Review by what1s1ove — CHANGES_REQUESTED** [review]

**Review by what1s1ove — APPROVED** [review]
